### ISSUE TITLE
Visual artifact running 'silent mode' in DOSBOX

### ISSUE THREAD

**Issue by Andy18650** [MobyGamer/XDC#3] opened 2021-01-11 14:01 UTC
The running the XDC_PLAY.EXE in DOSBOX with /q parameter in DOSBOX will result in 30%~50% pixels displayed correctly, but others are just filled with random patterns. This is worse when video mode is set to svga_s3. However, there is always a portion of pixels displayed correctly and the timing (i.e. framerate) also seemed correct.
I presume that this problem may be caused by imperfect emulation of 8253 by DOSBOX, therefore it shouldn't appear on a real PC.

**Comment by MobyGamer** [comment] 2021-01-13 05:37
I cannot reproduce this issue that you're seeing.  Please let me know which .EXE you are using, your exact command-line, and the video file you're trying to play.  I just now did this:

`xdc_play /q bigbuckb.xdv`

...and it played correctly in dosbox-x.  I had default settings, including mode=vga (the software was meant to run in mode=cga).

**Comment by Andy18650** [comment] 2021-01-13 08:15
https://user-images.githubusercontent.com/57994706/104418613-23514380-55b2-11eb-8397-6f2ba17519bf.mp4
(Note that the mp4 compression actually hides some artifact)
The DOSBOX I'm using is the latest official version (0.74-3) downloaded directly from www.dosbox.com. The XDC_PLAY used in this particular video is the 'party version' but the later version will work exactly the same way. 'core' setting doesn't matter, 'cycles' setting doesn't matter, 'machine' (CGA/VGA) …well it turns out that this doesn't matter either. The only reason that CGA feels better to me is because it has color while in VGA the gray image is mixed up with noise. I did more A-B comparison and figured out that the correct pixel ratio (and even distribution) is identical. Another false statement that I made in the issue (sorry...) is that the timing is correct, which is not. The 'corrupted' version actually plays slower.
One thing that does correct this problem is when I compiled one my own video with FPS set to 18.206, the very standard frequency of IRQ0. No artifacts are seen and the video plays exactly the same way in silent mode as SoundBlaster mode. (with no audio, of course) This gives me a clearer picture about the issue: DOSBOX either used some special trick emulating IRQ0 instead of emulating the full operation of the 8253 chip for some performance reasons; or it protects the chip from being written by any program. Therefore the XDC writes to 8253 register and believes that it works in the FPS of the video, but it's working at 18.206 FPS, which causes all the trouble. The only problem is that at 18.206FPS the program should have more time to load the pixels, and it shouldn't cause any trouble

**Comment by MobyGamer** [comment] 2021-01-13 16:23
Thanks for the example.  The "party version" player is buggy; do not use it.  I played LEADER.XDV without corruption using the latest player compiled from source in dosbox-x as well as dosbox 0.74-3.

Corrupted versions play slower because they are writing way more data (by mistake, due to a bug) to graphics memory.  That incorrect behavior does not have anything to do with 8253 emulation.

The reason your files under 20fps are not playing at the rate you expect can be explained by this code in the player:

```
  if intfps<20 then intfps:=20; {timer can only go as low as 18.2}
  play.callproc := soundIntCallerCGA;
  SetTimerHz(@noSoundIntCaller, intfps); {set to fire at video's rough framerate}
```

XDC was created specifically for 20fps or higher rates.

While it didn't matter for the testing, mode=cga is the intended use of the code as it was built completely for CGA graphics.

**Comment by Andy18650** [comment] 2021-01-13 23:56
OK, well, here comes the really weird stuff: yesterday I got my PC fixed and tried the player on it, the video is corrupted. (I made a wrong statement again, oh my god...) You are totally correct that this 'does not have anything to do with 8253 emulation'. Plus, this time I used the newer version (there is a clear difference in file size, 'party' is 22KB and the newer version is 15KB, so it's easy to tell).
The test setup is an original 5160 XT with 640KB onboard memory and no memory expansion card installed. It has the 8087 coprocessor, a floppy drive card connected to one floppy drive, an XT-IDE card as the boot device (since I just can't get a single MFM drive to work on my XT) and as the video source. And most importantly, it has an original IBM CGA card outputting to an IBM 5153 (this will give me a black-and-white video, I know). Probably everything on this setup, except the XT-IDE card and the keyboard, is IBM original. So it should behave 'like' a PC, and there is no way IBM can protect the 8253. So it DOES have nothing to do with emulation.

**Comment by MobyGamer** [comment] 2021-01-14 02:37
This puzzled me, so I recompiled every line of source, and I was able to reproduce the issue in dosbox.  With sound, it plays fine; without sound, it visually glitches.  I'm looking into it.

**Comment by Andy18650** [comment] 2021-01-14 03:30
I watched the corrupted video for minutes and found some pattern: static frame always leads to static noise frame. I've not seen a static correct frame (at least yet). Real-life videos is almost unrecognizable (for example, the first and second video showing dancing people and the 'Rickroll' part), but video with  less information such as the original Tron displays somewhat fine. Interestingly, the Tron: Legacy clip- a 'semi-real-life' video also plays fine although some frames look quite complex. An reason I can think about is that the clip has many black pixels so for the codec it's not so much of information.
The bad apple reveled more interesting details. It displays better than any of the other videos probably because of its simplicity (and because the 'input device' is so familiar to it!), and I often see changed pixels (deltas) 'wipe out' the glitch pattern. 
Another discovery is that the glitch pattern is not white noise, but horizontal bars that repeats vertically. However, the vertical height of the 'glitch bar' is not constant.
I come from the 6502 world (Apple II, in particular) and have just get my hands on PC and 8086/88 assembly, neither do I know about Pascal although I have experience in Java, python and C. So I think this is the best way I can help. I'm also digging into the code, learning everything in the way, so I will probably find the problem code later than you...

**Comment by MobyGamer** [comment] 2021-01-14 03:42
I found the bug and will be pushing a new version in the next hour.  The bug was:  When updating the screen, CX is used as the count for REP MOVS and REP STOS commands.  The compiler outputs MOV CX,count or MOV CL,count based on whether the value is 0xFF or less (CL) or 0x100 or higher (CX).  However, the compiler neglects to ensure that, if the very first count is 0xFF or less, to also ensure CH is clear.  So the very first MOVS or STOS will have garbage/unknown data in CH, making the entire CX count incorrect (and always larger than 0xFF).  Not only does this copy too much data, but it also results in SI pointing well past the actual data area of the frame.  So the later MOVS instructions have the correct count, but they're pulling from the wrong source.

The fix for this was simple:  I XOR CX,CX (make CX=0) before I CALL the frame update code.  Another way to fix this would be to fix the compiler to ensure the very first count load, if it isn't CX, makes CH=0 -- but you want to play older videos, so putting the fix into the player was quick and simple, and also saves more space (one XOR CX,CX in the player, vs. a XOR CX,CX added to thousands of frames in a video file).

This bug was never encountered with the sound code, because the sound code, by sheer luck, manages to clear CX before the frame code is called.

**Closed as completed** 2021-01-14 03:48 UTC
